### ISSUE TITLE
thinkphp6.0

### ISSUE THREAD

**Issue by Fucntion** [humSuperman/work-wechat#1]
composer无法完成安装。
这是我的composer.json

`
{
  "name": "qingclouds/service",
  "description": "qingclouds service framework",
  "type": "project",
  "keywords": [
    "qingclouds"
  ],
  "homepage": "http://plus.qingclouds.cn",
  "license": "Apache-2.0",
  "authors": [
    {
      "name": "function",
      "email": "function@qingclouds.cn"
    }
  ],
  "require": {
    "php": ">=7.2.5",
    "topthink/framework": "^6.0.0",
    "topthink/think-orm": "^2.0",
    "ext-curl": "*",
    "ext-json": "*",
    "ext-soap": "*",
    "ext-iconv": "*",
    "ext-openssl": "*",
    "ext-mbstring": "*",
    "ext-gd": "*",
    "ext-bz2": "*",
    "ext-dom": "*",
    "ext-fileinfo": "*",
    "topthink/think-multi-app": "^1.0",
    "phpmailer/phpmailer": "^6.5",
    "phpoffice/phpspreadsheet": "^1.20",
    "aliyuncs/oss-sdk-php": "^2.4",
    "endroid/qr-code": "^4.3",
    "topthink/think-queue": "^3.0",
    "zoujingli/wechat-developer": "^1.2",
    "zoujingli/weopen-developer": "^1.1",
    "php-mqtt/client": "^0.3.0",
    "wechatpay/wechatpay": "^1.4",
    "guzzlehttp/guzzle": "^7.4"

  },
  "require-dev": {
    "symfony/var-dumper": "^4.2",
    "topthink/think-trace": "^1.0"
  },
  "autoload": {
    "psr-4": {
      "app\\": "app"
    },
    "psr-0": {
      "": "extend/"
    }
  },
  "config": {
    "preferred-install": "dist"
  },
  "scripts": {
    "post-autoload-dump": [
      "@php think service:discover",
      "@php think vendor:publish"
    ]
  }
}
`

**Comment by Fucntion** [comment]
亲测这依赖是无需引入的，建议去掉。
illuminate/support
我在thinkphp6.0安装这个依赖，会导致composer的钩子运行错误。建议可以把这个依赖，抽出来放到合适的地方。
亲测本包是无需这个依赖的，如果有其他同学也一样困扰。可以看这个临时的包，如果作者看到并更正了，我就会把这个临时包删除。
https://packagist.org/packages/qingclouds/work-wechat-developer

这个包什么都没做，只是去掉了多余的依赖项。

**Comment by humSuperman** [comment]
感谢您的使用，已在[v1.1.0](https://github.com/humSuperman/work-wechat/releases/tag/v1.1.0)中移除了冗余引用。

因为公司项目使用的是laravel，未考虑thinkphp框架使用。

未来将会不定期实现企业微信的其他接口，再次感谢您的反馈。

**Comment by humSuperman** [comment]
感谢您的使用，已在[v1.1.0](https://github.com/humSuperman/work-wechat/releases/tag/v1.1.0)中移除了冗余引用。

因为公司项目使用的是laravel，未考虑thinkphp框架使用。

未来将会不定期实现企业微信的其他接口，再次感谢您的反馈。
